#ifndef __SMARTHOME_H_
#define __SMARTHOME_H_
#define ENDPOINT_ID_SMARTHOME 0X01
#define PROFILE_ID_SMARTHOME 0X501
#define DEVICE_ID_COORDINATOR 0X01
#define DEVICE_ID_LEDDEVICE 0X02
#define DEVIDE_VERSION_ID 0X0

#define LEDJOINNET_CMD_ID  0X1
#define TOGGLE_LED_CMD_ID  0X2
#define HEART_BEAT_CMD_ID  0X3
#define TEMP_HUMI_CMD_ID  0X4
#define MQ2_CMD_ID  0X5
#define LIGHT_CMD_ID  0X6
#define HEART_BEAT_MAX_COUNT 10

#define TIMER_TIMEOUT_EVT 0X01
#define READ_DHT11_EVENT 0X02
#define READ_MQ2_EVENT 0X03
#define READ_LIGHT_EVENT 0X04

#endif